### ISSUE TITLE
PubMed/eutils lookup bug

### ISSUE THREAD

**Issue by oneilsh** [monarch-initiative/oai-monarch-plugin#61]
This might be intermittent - occurred initially when trying to access `https://oai-monarch-plugin.monarchinitiative.org/disease-phenotypes?disease_id=MONDO%3A0019391&limit=10&offset=0`.

```
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/oai-monarch-plugin-9TtSrW0h-py3.10/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/.cache/pypoetry/virtualenvs/oai-monarch-plugin-9TtSrW0h-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/oai-monarch-plugin-9TtSrW0h-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/oai-monarch-plugin-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/oai-monarch-plugin-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/oai-monarch-plugin-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/.cache/pypoetry/virtualenvs/oai-monarch-plugin-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/oai-monarch-plugin-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/app/src/oai_monarch_plugin/middlewares.py", line 16, in __call__
    response = await call_next(request)
  File "/root/.cache/pypoetry/virtualenvs/oai-monarch-plugin-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/root/.cache/pypoetry/virtualenvs/oai-monarch-plugin-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/root/.cache/pypoetry/virtualenvs/oai-monarch-plugin-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/oai-monarch-plugin-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/.cache/pypoetry/virtualenvs/oai-monarch-plugin-9TtSrW0h-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/root/.cache/pypoetry/virtualenvs/oai-monarch-plugin-9TtSrW0h-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/oai-monarch-plugin-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/oai-monarch-plugin-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/oai-monarch-plugin-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/root/.cache/pypoetry/virtualenvs/oai-monarch-plugin-9TtSrW0h-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/root/.cache/pypoetry/virtualenvs/oai-monarch-plugin-9TtSrW0h-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/src/oai_monarch_plugin/routers/disease_to_phenotype.py", line 53, in get_disease_phenotype_associations
    assoc.publications.append(get_pub_info(pub))
  File "/app/src/oai_monarch_plugin/routers/utils.py", line 80, in get_pub_info
    data = next(iter(ec.efetch(db='pubmed', id = pmid)))
  File "/root/.cache/pypoetry/virtualenvs/oai-monarch-plugin-9TtSrW0h-py3.10/lib/python3.10/site-packages/eutils/_internal/client.py", line 83, in efetch
    xml = self._qs.efetch({"db": db, "id": str(id)})
  File "/root/.cache/pypoetry/virtualenvs/oai-monarch-plugin-9TtSrW0h-py3.10/lib/python3.10/site-packages/eutils/_internal/queryservice.py", line 142, in efetch
    return self._query("/efetch.fcgi", args)
  File "/root/.cache/pypoetry/virtualenvs/oai-monarch-plugin-9TtSrW0h-py3.10/lib/python3.10/site-packages/eutils/_internal/queryservice.py", line 318, in _query
    raise EutilsNCBIError("Error parsing response object from NCBI: {}".format(ex))
eutils._internal.exceptions.EutilsNCBIError: Error parsing response object from NCBI: Bad Request (400): Unknown Error
```

**Comment by oneilsh** [comment]
Calling this closed for now until better testing can be done

**Comment by oneilsh** [comment]
Going to reopen this one as I don't think this change has been pushed to production yet. @kevinschaper , do you know more?
